### ISSUE TITLE
add javadoc

### ISSUE THREAD

**Issue by monkey999por-sub** [monkey999por/translation#3]
Correspond by branch add-javaDoc 
 Many unmaintained documents

**Comment by monkey999por** [comment]
complete package "setting" by ed5a550 and f6f38c4

**Comment by monkey999por** [comment]
complete Main.java by 69d36c135c96c958314066b413f8371c749e704a

**Comment by monkey999por** [comment]
complete package "worker" by ec09b824f7dfba72e267cff46b019f7a32f387ef

**Comment by monkey999por** [comment]
complete package "thread" by 4c8583525e6207261cf64b8d2ce0e4f928fa42d8

**Comment by monkey999por** [comment]
complete package "common" by 793832fa9621441c8d33cfce5068fc19fc7b3729

**Comment by monkey999por** [comment]
complete package "client" by c9699efa69a3c4e7d77f96407b964dd820b9c59a
